a few more tests

diff --git a/crccheck/check-the-checker b/crccheck/check-the-checker
--- a/crccheck/check-the-checker
+++ b/crccheck/check-the-checker
@@ -13,14 +13,22 @@ verify_check_patchset_fails() {
 	fi
 }
 
+finish() {
+	if [ -e "$TMPDIR" ]; then
+		echo "Temporary directory is: $TMPDIR"
+	fi
+}
+trap finish EXIT
+
+
 # make a copy of the current repo that we can play with
 cd ${TMPDIR}
 mkdir misc-files
 git clone ${CURR_ROOT} vpp-uut
 cd vpp-uut
 
-# grab the CRC checker
-git fetch "https://gerrit.fd.io/r/vpp" refs/changes/81/26881/11 && git cherry-pick FETCH_HEAD
+# maybe grab the CRC checker
+# git fetch "https://gerrit.fd.io/r/vpp" refs/changes/81/26881/13 && git cherry-pick FETCH_HEAD || echo "Already there"
 
 
 echo "TEST 1: Check the current patchset..."
@@ -69,8 +77,43 @@ git add crccheck.api
 git commit -m "deprecated api";
 extras/scripts/crcchecker.py --check-patchset
 
-echo "Current directory: $(pwd)"
-exit 0;
+echo "TEST 8: Verify that we can not rename a non-deprecated message"
+sed -i -e 's/crccheck_2/crccheck_3/g' crccheck.api
+git add crccheck.api
+git commit -m "renamed api";
+verify_check_patchset_fails
+# fix it.
+sed -i -e 's/crccheck_3/crccheck_2/g' crccheck.api
+git commit -a --amend -m "empty commit after we renamed api back" --allow-empty
+
+echo "TEST 9: Verify that the check fails if the changes are not committed"
+cat >>crccheck.api <<EOL
+autoreply define crc_new_check_in_progress
+{
+  option status="in_progress"
+  bool foobar;
+};
+EOL
+verify_check_patchset_fails
+
+echo "TEST10: Verify that the in-progress message can be added"
+git add crccheck.api
+git commit -m "added a new in-progress api";
+extras/scripts/crcchecker.py --check-patchset
+
+echo "TEST11: Verify we can rename an in-progress API"
+sed -i -e 's/crc_new_check_in_progress/crc_new_check_in_progress_2/g' crccheck.api
+git add crccheck.api
+git commit -m "renamed in-progress api";
+extras/scripts/crcchecker.py --check-patchset
+
+echo "TEST12: Verify we can add a field to an in-progress API"
+sed -i -e 's/foobar;/foobar; bool new_baz;/g' crccheck.api
+git add crccheck.api
+git commit -m "new field added in in-progress api";
+extras/scripts/crcchecker.py --check-patchset
+
+
 echo "TEST: All tests got the expected result, cleaning up."
 
 # done with all the tests - clean up
